---

- name: Reload samba
  service: name={{ item }} state=reloaded
  with_items: "{{ samba_service_name }}"
  register: reloaded
  ignore_errors: True
  notify: Restart samba

- name: Restart samba
  service: name={{ item.item }} state=restarted
  when: item|failed
  with_items: reloaded.results


